### ISSUE TITLE
joystick becomes unresponsive when moving between wifi access points, or loss of signal

### ISSUE THREAD

**Issue by ethanrublee** [farm-ng/tractor#51]
I think this has something to do with wifi/bluetooth, it seems like we don't get packets from the joystick when the wifi is sketchy.

This may help:
```
farmer@tractor0003:~$ sudo cat /etc/modprobe.d/iwlwifi.conf
# /etc/modprobe.d/iwlwifi.conf
# iwlwifi will dyamically load either iwldvm or iwlmvm depending on the
# microcode file installed on the system.  When removing iwlwifi, first
# remove the iwl?vm module and then iwlwifi.
remove iwlwifi \
(/sbin/lsmod | grep -o -e ^iwlmvm -e ^iwldvm -e ^iwlwifi | xargs /sbin/rmmod) \
&& /sbin/modprobe -r mac80211

options iwlwifi bt_coex_active=0
```

https://wiki.archlinux.org/index.php/Network_configuration/Wireless#Bluetooth_coexistence
https://wireless.wiki.kernel.org/en/users/Drivers/iwlwifi#wi-fibluetooth_coexistence

Will paste logs when I can get them.

**Comment by ethanrublee** [comment]
this seems to help, needs more testing A/B to be sure but in a 10 minute run around the field didn't see any missed cycles in the farm_ng.steering program, and only a few minor missed periods in the farm_ng.tractor controller program.

**Comment by ethanrublee** [comment]
Another issue seems to be in event bus handling - we're using ip addresses assigned by dhcp and not localhost when possible.

```
Sep 02 20:37:17 tractor0003 steering.sh[5496]: OSError: [Errno 101] Network is unreachable
Sep 02 20:37:17 tractor0003 steering.sh[5496]: ERROR:asyncio:Exception in callback Periodic._read_timer()
Sep 02 20:37:17 tractor0003 steering.sh[5496]: handle: <Handle Periodic._read_timer()>
Sep 02 20:37:17 tractor0003 steering.sh[5496]: Traceback (most recent call last):
Sep 02 20:37:17 tractor0003 steering.sh[5496]:   File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
Sep 02 20:37:17 tractor0003 steering.sh[5496]:     self._callback(*self._args)
Sep 02 20:37:17 tractor0003 steering.sh[5496]:   File "/home/farmer/tractor/python/farm_ng/periodic.py", line 27, in _read_timer
Sep 02 20:37:17 tractor0003 steering.sh[5496]:     self.callback(n_periods)
Sep 02 20:37:17 tractor0003 steering.sh[5496]:   File "/home/farmer/tractor/python/farm_ng/steering.py", line 79, in send
Sep 02 20:37:17 tractor0003 steering.sh[5496]:     get_event_bus('steering').send(make_event(_g_message_name, self._command))
Sep 02 20:37:17 tractor0003 steering.sh[5496]:   File "/home/farmer/tractor/python/farm_ng/ipc.py", line 143, in send
Sep 02 20:37:17 tractor0003 steering.sh[5496]:     self._mc_send_sock.sendto(buff, (service.host, service.port))
Sep 02 20:37:17 tractor0003 steering.sh[5496]: OSError: [Errno 101] Network is unreachable
```

Seems like should detect if host is local and force the host to 127.0.0.1, or go for a static configuration in the event_bus.
